[pytest]
testpaths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --color=yes --alluredir=./allure-results --clean-alluredir
markers =
    smoke: 冒烟测试
